### ISSUE TITLE
Something Broke...

### ISSUE THREAD

**Issue by Pelonza** [Azure/Azure-TDSP-Utilities#22]
I had students using the IDEAR tool two weeks ago without any real problems, but this week I had a different student download the whole package and had issues getting the code to run even on the sample data.

One: Iine 31 of the IDEAR.rmd there's a floating "css: style.css" that seems to stop the r-markdown from actually running. 

After commenting it out we seemed to be able to get it running, though we were still having version of R and pandoc issues (had to install the newest version for it to work).

**Comment by Pelonza** [comment]
I'd strongly encourage you to include a "version check" of R (and probably all the packages too). Without that, there's some issues with checking for specific PACKAGES, because some required packages can't be installed in older versions of R.

**Comment by xibingaomsft** [comment]
Thanks for reporting the issue. The "css:style.css" issue was due to garbled text introduced when we applied hotfix; now it is fixed. In the IDEAR R [readme](https://github.com/Azure/Azure-TDSP-Utilities/tree/master/DataScienceUtilities/DataReport-Utils/R), we recommended using R 3.3.1 or 3.3.2. We will make improvement in later releases to make package installation experience smoother.
